---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: contrail-redis
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: contrail-redis
  template:
    metadata:
      labels:
        app: contrail-redis
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      serviceAccountName: contrail-service-account
      initContainers:
      - name: contrail-k8s-init
        image: {{ .Values.global.containerRegistry }}/contrail-k8s-init-container:{{ .Values.global.containerTag }}
        command: ["/contrail-k8s-init","contrail-redis"]
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: wait-for-vhost0
        image: busybox
        command: ["sh","-c","until ifconfig vhost0 > /dev/null 2>&1; do sleep 1;echo waiting for vhost0 ;done;echo vhost0 is alive"]
      containers:
      - name: redis
        image: "{{ .Values.global.containerRegistry }}/contrail-external-redis:{{ .Values.global.containerTag }}"
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: contrail-config-map
        env:
        - name: CONTROLLER_NODES
          valueFrom:
            configMapKeyRef:
              name: contrailcontrollernodesv1
              key: CONTROLLER_NODES
        volumeMounts:
        - mountPath: /var/lib/redis
          name: redis-data
        - mountPath: /var/log/redis
          name: redis-logs
      volumes:
      - name: redis-data
        hostPath:
          path: /var/lib/contrail/redis
      - name: redis-logs
        hostPath:
          path: /var/log/contrail/redis
